[package]
name = "macro_engine"
version = "0.3.0"
authors = ["Tanner <Tanner@NorthPeak.Software>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enigo = "0.3.0"
rand = "0.9.0"
